name: "Default Palette"
description: "Classic earthy tones"
colors:
  - name: "Grass Green"
    r: 0.2
    g: 0.6
    b: 0.2
  - name: "Dirt Brown"
    r: 0.5
    g: 0.3
    b: 0.1
  - name: "Light Gray"
    r: 0.7
    g: 0.7
    b: 0.7
  - name: "Tan"
    r: 0.8
    g: 0.6
    b: 0.3
  - name: "Dark Gray"
    r: 0.4
    g: 0.4
    b: 0.4
  - name: "Blue"
    r: 0.2
    g: 0.4
    b: 0.8
  - name: "Red"
    r: 0.9
    g: 0.2
    b: 0.2
  - name: "Yellow"
    r: 1.0
    g: 0.8
    b: 0.2
  - name: "Purple"
    r: 0.6
    g: 0.3
    b: 0.6
  - name: "Orange"
    r: 1.0
    g: 0.5
    b: 0.3
  - name: "Cyan"
    r: 0.2
    g: 0.8
    b: 0.8
  - name: "White"
    r: 0.95
    g: 0.95
    b: 0.95
